### ISSUE TITLE
Stop pruning one step before passing accuracy threshold

### ISSUE THREAD

**Issue by abigailgold** [IBM/ai-privacy-toolkit#17]
After calculating the initial accuracy achieved by the generalizations derived from the decision tree leaves, there are two directions in which the algorithm can proceed: improving accuracy (to get above the threshold) or improving generalizations (while reducing accuracy). The second direction will at some point will cause the accuracy to go below the desired threshold (the last iteration of the loop that is run). But when this happens, the generalizations need to be rolled back to the previous state, the one where the target accuracy was not passed. This can be done either by storing locally the generalizations and generalized data from the previous loop iteration and replacing them when the threshold is passed, or by only "speculatively" applying the generalizations in each iteration, and applying them finally only if the threshold was not passed.

**Comment by olasaadi** [comment]
I do not think that after the whole run you can get accuracy < target accuracy, because if it started with improving generalizations to reduce accuracy and in the last iteration passed the target accuracy it will enter the loop of improving accuracy to get above threshold and finish the run .
Can you please send me the test that show you what you discovered to check this
Anyway, I can do the way you said above to not pass target accuracy if it is more correct

**Comment by abigailgold** [comment]
That's exactly what I don't want to happen because going into the second loop will harm the generalizations much more, and moreover it may never be able to get back to the same accuracy (both loops are not symmetric). The correct way is to stop the loop before passing the threshold.
Thanks.

**Comment by abigailgold** [comment]
Resolved in sup cat features merge.
